In [3]:
from quantbullet.utils.data import generate_fake_bond_trades
from datetime import date

In [8]:
START_DATE = date( 2025, 1, 1 )
END_DATE = date( 2025, 2, 1 )

df = generate_fake_bond_trades( start_date=START_DATE, end_date=END_DATE, 
                                random_state=42, cluster_by_rating=True,
                                theo_coefficients=( 0.15, 0.25, 0, 0 ),
                                response_std=0.3)

In [11]:
df

,date,ticker,rating,feature_A,feature_B,feature_C,feature_D,expiry,yield
0,2025-01-01,TICK008 AAA,AAA,10.993428,19.723471,6.476885,15.230299,2027-04-25,6.509636
1,2025-01-01,TICK002 AAA,AAA,9.531726,23.158426,7.674347,-4.694744,2033-02-10,7.382133
2,2025-01-01,TICK048 AAA,AAA,9.073165,19.068540,2.419623,-19.132802,2032-05-15,5.610634
3,2025-01-01,TICK018 AAA,AAA,8.875425,17.974338,3.142473,-9.080241,2032-12-12,5.401207
4,2025-01-01,TICK016 AAA,AAA,12.931298,19.548447,0.675282,-14.247482,2031-03-13,6.663492
...,...,...,...,...,...,...,...,...,...
2900,2025-02-01,TICK047 B,B,62.345789,70.034138,7.966842,7.180620,2033-05-01,27.022115
2901,2025-02-01,TICK041 B,B,59.355976,70.344118,-5.883616,0.128143,2032-08-03,26.138879
2902,2025-02-01,TICK033 B,B,58.418752,69.435376,-9.437054,-5.050173,2034-05-19,26.072479
2903,2025-02-01,TICK046 B,B,60.804525,71.898515,-4.637844,13.351046,2028-05-07,27.376891
2904,2025-02-01,TICK010 B,B,61.008188,70.307298,3.191208,11.870512,2026-02-17,27.095127